name: checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  format-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: ./.github/actions/setup
      - name: Run Formatter
        run: |
          nix run nixpkgs#nixfmt-tree -- --ci

  flake-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: ./.github/actions/setup
      - name: Check Flake
        run: |
          nix flake check
